# =============================================================================
# ParkSim OS — Terraform Deploy Script
# Provisions real AWS EC2 instance
# =============================================================================

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  ParkSim OS - Terraform AWS Deployment" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

$terraformDir = Join-Path $PSScriptRoot "terraform"
Set-Location $terraformDir

# ─── Step 1: Init ─────────────────────────────────────────────────────────────
Write-Host "[1/3] Initializing Terraform (downloading AWS provider)..." -ForegroundColor Yellow
terraform init
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: terraform init failed!" -ForegroundColor Red; exit 1 }
Write-Host "  -> Init complete!" -ForegroundColor Green

# ─── Step 2: Plan ─────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "[2/3] Running Terraform Plan (preview of AWS resources)..." -ForegroundColor Yellow
Write-Host "      (This is what you SHOW to ma'am - real infra plan)" -ForegroundColor Cyan
Write-Host ""
terraform plan -out=tfplan
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: terraform plan failed!" -ForegroundColor Red; exit 1 }

# ─── Step 3: Apply ────────────────────────────────────────────────────────────
Write-Host ""
$confirm = Read-Host "Do you want to CREATE the EC2 instance on AWS now? (yes/no)"
if ($confirm -eq "yes") {
    Write-Host ""
    Write-Host "[3/3] Applying Terraform - Creating EC2 on AWS..." -ForegroundColor Yellow
    terraform apply tfplan
    if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: terraform apply failed!" -ForegroundColor Red; exit 1 }

    # Get the output
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host "  EC2 Instance Created Successfully!" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Green
    Write-Host ""
    $ec2Ip = terraform output -raw public_ip
    Write-Host "  EC2 Public IP: $ec2Ip" -ForegroundColor Cyan
    Write-Host "  App URL:       http://$ec2Ip" -ForegroundColor Cyan
    Write-Host "  SSH Command:   ssh -i ~/.ssh/id_rsa ubuntu@$ec2Ip" -ForegroundColor Cyan

    # Auto-update Ansible inventory
    Write-Host ""
    Write-Host "Updating Ansible inventory with EC2 IP..." -ForegroundColor Yellow
    $inventoryPath = Join-Path $PSScriptRoot "ansible\inventory.ini"
    $inventoryContent = @"
[ec2]
# ─────────────────────────────────────────────────────────────────────────────
# Auto-generated by terraform-deploy.ps1
# EC2 IP: $ec2Ip
# ─────────────────────────────────────────────────────────────────────────────
$ec2Ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'
"@
    $inventoryContent | Out-File -FilePath $inventoryPath -Encoding ASCII
    Write-Host "  -> inventory.ini updated with IP: $ec2Ip" -ForegroundColor Green

    # Save EC2 IP for Jenkins
    $ec2Ip | Out-File -FilePath (Join-Path $PSScriptRoot ".ec2-ip") -Encoding ASCII
    Write-Host "  -> EC2 IP saved to .ec2-ip file" -ForegroundColor Green

    Write-Host ""
    Write-Host "NEXT STEP: Wait 2-3 minutes for EC2 to boot, then run:" -ForegroundColor Yellow
    Write-Host "  WSL: cd ansible && bash run-ansible.sh" -ForegroundColor Cyan
} else {
    Write-Host "Apply cancelled. EC2 was NOT created." -ForegroundColor Yellow
    Write-Host "Run this script again when ready." -ForegroundColor Yellow
}

Set-Location $PSScriptRoot
